### ISSUE TITLE
Allow index.html for the index file of a directory

### ISSUE THREAD

**Issue by dcmouyard** [forumone/puppet-forumone#10]
Mike suggested using `try_files $uri $uri/index.html @rewrite;` on line 37 of https://github.com/forumone/puppet-forumone/blob/1.1.x/templates/webserver/nginx/vhost_drupal.erb

**Comment by dcmouyard** [comment]
The above fix worked for me on a recent project.

**Comment by wwhurley** [comment]
You can enable this by changing the Puppetfile to replace the line for `forumone/forumone` to the following:

```
mod "forumone/forumone",
  :git => "https://github.com/forumone/puppet-forumone.git",
  :ref => "1.1.x"
```
