### ISSUE TITLE
Iptables is not updated when integrating webstarter back into Project

### ISSUE THREAD

**Issue by generalconsensus** [forumone/puppet-forumone#37]
AC: 

As a dev, I want to make sure that I can re-integrate webstarter/puppet-forumone back into my project with the automated testing changes. 

The project.pp (https://github.com/forumone/puppet-forumone/blob/1.1.x/manifests/os/fedora/project.pp#L1) file doesn't appear to be running and updating iptables during a vagrant provision after re-integrating the latest webstarter/puppet-forumone work:
1. Vagrant ports: 

![](https://www.evernote.com/l/AFOJeW8L7NFLxZSSASmKGNL0lhwkH8rr1r8B/image.png)
1.  Iptables ports:

![](https://www.evernote.com/l/AFM6s_g9mKtK9rRYN3URdzMYmjj_Vt5YuDAB/image.png)

**Comment by wwhurley** [comment]
For this project the ports are already being set in the `localhost.localdomain.yaml` file in `puppet/manifests/hieradata/sites` directory.

**Comment by generalconsensus** [comment]
Great, that solved my issue -- thanks!
